version: '3.8'
services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal -d temporal"]
      interval: 5s
      timeout: 5s
      retries: 10

  temporal:
    image: temporalio/auto-setup:1.24
    environment:
      DB: postgres12
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
      POSTGRES_HOST: postgres
      POSTGRES_SEEDS: postgres
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "7233:7233"
    volumes:
      - temporal-data:/temporal

  temporal-ui:
    image: temporalio/ui:2.15.0
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - "8088:8080"
    depends_on:
      - temporal

  api:
    build: ./
    command: ["/app/api"]
    environment:
      - CONFIG_PATH=/config/config.yaml
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
    depends_on:
      - temporal

  worker:
    build: ./
    command: ["/app/worker"]
    environment:
      - CONFIG_PATH=/config/config.yaml
    volumes:
      - ./config:/config
    depends_on:
      - temporal

volumes:
  temporal-data:
  postgres-data:
