# Afrikpay Gateway - Configuration Centralisée
# ============================================

# ================================
# CONFIGURATION GÉNÉRALE
# ================================
app:
  name: "afrikpay-gateway"
  version: "1.0.0"
  environment: "development"
  debug: true

# ================================
# SERVICES CONFIGURATION
# ================================
services:
  auth:
    port: 8001
    host: "0.0.0.0"
    jwt:
      private_key_path: "./config/keys/private.pem"
      public_key_path: "./config/keys/public.pem"
      expiration_hours: 24
      refresh_expiration_hours: 168
      issuer: "afrikpay-gateway"
      audience: "afrikpay-users"
    
  crud:
    port: 8002
    host: "0.0.0.0"
    database:
      uri: "mongodb://admin:password123@localhost:27017/afrikpay?authSource=admin"
      name: "afrikpay"
      timeout: "10s"
      max_pool_size: 100
      min_pool_size: 5
    
  temporal:
    port: 8003
    host: "0.0.0.0"
    server:
      host: "localhost:7233"
      namespace: "default"
      task_queue: "afrikpay-tasks"
    workflows:
      crypto_purchase_timeout: "30m"
      wallet_deposit_timeout: "15m"
      retry_policy:
        initial_interval: "1s"
        backoff_coefficient: 2.0
        maximum_interval: "100s"
        maximum_attempts: 3

# ================================
# BASES DE DONNÉES
# ================================
databases:
  mongodb:
    host: "localhost"
    port: 27017
    username: "admin"
    password: "password123"
    database: "afrikpay"
    auth_source: "admin"
    
  postgresql:
    host: "localhost"
    port: 5432
    username: "temporal"
    password: "temporal123"
    database: "temporal"
    ssl_mode: "disable"

# ================================
# APIS EXTERNES
# ================================
external_apis:
  binance:
    base_url: "https://testnet.binance.vision"
    api_key: "Bjhd5FsunILOwVT1RXJiUxOhZt7MQ2jydKs2jspF11kB6tv1xY3EAmDJvrR4w8la"
    api_secret: "LIWTukFxAjUH43qx7upKrADY1q8Ogc46OLMbeqgsv98noMvV7mWkGeseKtgUmbtC"
    timeout: "30s"
    rate_limit: 1200  # requests per minute
  
  bitget:
    base_url: "https://api.bitget.com"
    api_key: "bg_cd4956801e3a93c80ca41fe85f473abd"
    api_secret: "a364ff45a818c9f2273cb7e362bfdb74939640c343a2bae87d1687ce6fdaa034"
    timeout: "30s"
    rate_limit: 10000  # requests per hour
    
  mtn_momo:
    base_url: "https://sandbox.momodeveloper.mtn.com"
    primary_key: "1ab732916da44b82be43abf6d6d17b47"
    secondary_key: "6607bfe1797e449c8b0e5ed45121ad3d"
    timeout: "30s"
    rate_limit: 100  # requests per minute
    
  orange_money:
    base_url: "https://api.orange.com/orange-money-webpay/dev/v1"
    client_id: "LNAzgV2wqco8pwbx8iKPbAM5C2qyAzHB"
    client_secret: "NTOIQfmN22APwNcoCPBKBbexsHpOIwxTxVDaZYu7smOf"
    authorization: "Basic TE5BemdWMndxY284cHdieDhpS1BiQU01QzJxeUF6SEI6TlRPSVFmbU4yMkFQd05jb0NQQktCYmV4c0hwT0l3eFR4VkRhWll1N3NtT2Y="
    timeout: "30s"
    rate_limit: 100  # requests per minute
    

# ================================
# SÉCURITÉ
# ================================
security:
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
    max_age: 86400
    
  rate_limiting:
    requests_per_minute: 100
    burst_size: 10
    
  timeouts:
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "120s"

# ================================
# LOGGING
# ================================
logging:
  level: "debug"  # debug, info, warn, error
  format: "json"  # json, text
  output: "stdout"  # stdout, file
  file_path: "./logs/app.log"
  max_size: 100  # MB
  max_backups: 5
  max_age: 30  # days
  compress: true

# ================================
# MONITORING
# ================================
monitoring:
  prometheus:
    enabled: true
    port: 9090
    path: "/metrics"
    
  health_check:
    enabled: true
    path: "/health"
    interval: "30s"
    
  tracing:
    enabled: true
    jaeger_endpoint: "http://localhost:14268/api/traces"
    service_name: "afrikpay-gateway"

# ================================
# CIRCUIT BREAKER
# ================================
circuit_breaker:
  max_requests: 3
  interval: "60s"
  timeout: "30s"
  failure_threshold: 5
  success_threshold: 2

# ================================
# RETRY POLICY
# ================================
retry_policy:
  max_attempts: 3
  initial_delay: "1s"
  max_delay: "30s"
  multiplier: 2.0
  jitter: true
