### Create User
POST http://localhost:8002/users
Content-Type: application/json

{
  "id": "u123",
  "email": "alice@example.com",
  "role": "user",
  "password_hash": "hashedPwd"
}

### Get User
GET http://localhost:8002/users/u123

### Create Wallet
POST http://localhost:8002/wallets
Content-Type: application/json

{
  "id": "w1",
  "user_id": "u123",
  "balance": 0,
  "currency": "USDT"
}

### Create Transaction
POST http://localhost:8002/transactions
Content-Type: application/json

{
  "id": "t1",
  "wallet_id": "w1",
  "amount": 50,
  "type": "deposit"
}
