# Afrikpay Gateway - Configuration Centralisée
# ============================================

binance:
  base_url: "https://testnet.binance.vision"
  api_key: "Bjhd5FsunILOwVT1RXJiUxOhZt7MQ2jydKs2jspF11kB6tv1xY3EAmDJvrR4w8la"
  api_secret: "LIWTukFxAjUH43qx7upKrADY1q8Ogc46OLMbeqgsv98noMvV7mWkGeseKtgUmbtC"
  timeout: "30s"
  rate_limit: 1200  # requests per minute

bitget:
  base_url: "https://api.bitget.com"
  api_key: "bg_688e18af62fd23f63256cda0e25cc6e9"
  api_secret: "37b51bfea417288f91bc08cd38a9a9c41e92c1ce0bf686ebbca833eafa2f32d5"
  passphrase: "afrikpaygateway"
  timeout: "30s"
  rate_limit: 10000  # requests per hour

mtn_momo:
  base_url: "https://sandbox.momodeveloper.mtn.com"
  primary_key: "d3a8f9bfaad746ae9221a99cf40f5d12"
  secondary_key: "72d3ac51e62f49af83b9c854fe427bd5"
  timeout: "30s"
  rate_limit: 100  # requests per minute
  
orange_money:
  base_url: "https://api.orange.com/orange-money-webpay/dev/v1"
  client_id: "LNAzgV2wqco8pwbx8iKPbAM5C2qyAzHB"
  client_secret: "NTOIQfmN22APwNcoCPBKBbexsHpOIwxTxVDaZYu7smOf"
  authorization: "Basic TE5BemdWMndxY284cHdieDhpS1BiQU01QzJxeUF6SEI6TlRPSVFmbU4yMkFQd05jb0NQQktCYmV4c0hwT0l3eFR4VkRhWll1N3NtT2Y="
  timeout: "30s"
  rate_limit: 100  # requests per minute

crud:
  base_url: "http://localhost:8002"
  timeout: "30s"
  rate_limit: 1000  # requests per minute

# ================================
# CIRCUIT BREAKER & RETRY POLICY
# ================================
temporal:
  server:
    address: "localhost:7233"
  api:
    address: "localhost"
    port: 8088
  circuit_breaker:
    max_requests: 3
    interval: "60s"
    timeout: "30s"
    failure_threshold: 5
    success_threshold: 2
  retry_policy:
    max_attempts: 3
    initial_delay: "1s"
    max_delay: "30s"
    multiplier: 2.0
    jitter: true
